# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        sudo apt-get upgrade
        sudo apt-get update
        echo install linux-image-extra-$(uname -r)
        sudo apt install linux-image-azure
        cd /lib/modules/
        find . -name mac80211_hwsim.ko
        echo check ip netns
        sudo ip netns add blue
        sudo ip netns list
        sudo ip netns del blue
        echo check 80211.
        sudo modprobe mac80211_hwsim
        sudo lsmod | grep  mac80211_hwsim
